### ISSUE TITLE
Property.id() doesn't exist on the package

### ISSUE THREAD

**Issue by BrightkyEfoo** [tuanvu0995/adonisjs-graphql#6]
When installing the package to my adonis project, 
Property.id() doesn't exist.

**Comment by BrightkyEfoo** [comment]
You have to rebuild it and push again, plz

**Comment by tuanvu0995** [comment]
Hi @BrightkyEfoo , thank you for your interest in and testing my package.
> When installing the package to my adonis project, Property.id() doesn't exist.

Because the latest changes are not yet available in version `v0.0.1-next.4`. Currently, for the ID field, you can use `@Property()` (string) or `@Property({type: () => Int})` if you want.

> You have to rebuild it and push again, plz

Sure, let me do some cleanup and create a new release.

**Comment by BrightkyEfoo** [comment]
Guy, the work you did is great. Really great. 

I hope I can help.

Another thing, when do you think you will have published the next release, I am quite impatient to test everything and give you further feedback, which I hope will help the project grow.

**Comment by tuanvu0995** [comment]
> Guy, the work you did is great. Really great.
I hope I can help.

Thank you so much @BrightkyEfoo .

> Another thing, when do you think you will have published the next release, I am quite impatient to test everything and give you further feedback, which I hope will help the project grow.

Yes, I plan to release it right after completing the major features. Currently, I'm stuck on extending an object type. I hope to finish it early next week, but for now, I will release the next version in 30 minutes.

I'm very excited to receive feedback from you.

**Comment by BrightkyEfoo** [comment]
me too, I am very excited about the final result. And thank you again.

Do you have a correspondent in Africa? In Cameroon precisely. 

If you agree we can exchange WhatsApp. 

Your mastery of language is at least at the level I want to reach. 

For the moment I don't understand the whole of your code, but I'm sure that if even once a month we discussed then after 6 months I would be much better. 

Do you want to be a correspondent?

**Comment by tuanvu0995** [comment]
Unfortunately, I am currently living in Vietnam (Asia). I think I can contact you via Telegram because I don't use WhatsApp, and my English (listening and speaking) is not very good, so we might not understand each other well.

So, I can explain everything about the source code through text. Are you okay with this?

**Comment by BrightkyEfoo** [comment]
Yesss, gime your telegram.

**Comment by BrightkyEfoo** [comment]
Me too my English is not good 😊

**Comment by tuanvu0995** [comment]
Here is my telegram: https://t.me/timlai
